### PR TITLE
Add articles about how to setup the new presets feature

### PR DESCRIPTION
**Pull request by Jeehut**
Please take a look at this. I would like to discuss both the purchases article and the errors article. For example, the fact that there is some code I wrote there on how to get the country code, the purchase type, and how to convert other currencies to USD (which is a requirement of the feature for comparison reasons). We could also build these things into the different clients, or at least for the Swift client and update the documentation.

Note also that I put a link to a Freemium 3rd-party service as a convenience on how to do currency conversion for free. Not sure if outside links are allowed in the docs, so looking forward to your feedback.

This should be merged together with https://github.com/TelemetryDeck/SwiftClient/pull/154.

### CODE REVIEW

**Comment by Jeehut** [comment]
@winsmith I still haven't received feedback on this question, what's your take on it?

> Note also that I put a link to a Freemium 3rd-party service as a convenience on how to do currency conversion for free. Not sure if outside links are allowed in the docs, so looking forward to your feedback.

**Comment by Jeehut** [comment]
@winsmith I have now also finished up the Errors article. Please take a look.

I have to admit there's some setup needed to get these presets working. I think it would be better if the official mobile SDKs (Swift, Android, Flutter) all came with some built-in code that make the setup process much simpler. For the "Purchases" in particular, I think our SDKs could include a currency converter with data we update every few months. We're not promising exact numbers anyways, and currency conversion doesn't change too much, so an update every few months or so should be fine. I could even write a script to automate it. But please read the articles first and give me feedback what you think.

**Comment by Jeehut** [comment]
@winsmith I just updated the preset documentation based on the grand rename and added convenience methods for the Swift SDK. The other SDK might want to implement similar conveniences, but they are not required, the docs explain how to set it up without the convenience of the SDK.

This is ready to merge, but currently targets the grand-rename branch. You might want to merge #85 first, then edit the target branch of this to the `main` (with the edit button at the top active you can edit branches of a PR) and then merge.

**Comment by winsmith** [comment]
Hi sorry I somehow overlooked this PR. I think this is awesome. Here are some answers:

> We could also build these things into the different clients, or at least for the Swift client and update the documentation.

Yes, let's aim for that in the future, but not promise anything right now. I've already made some plans for error tracking and metrics and I want to be on the same page with you first. 

> Note also that I put a link to a Freemium 3rd-party service as a convenience on how to do currency conversion for free. Not sure if outside links are allowed in the docs, so looking forward to your feedback.

I think links are totally allowed.

> I have to admit there's some setup needed to get these presets working. I think it would be better if the official mobile SDKs (Swift, Android, Flutter) all came with some built-in code that make the setup process much simpler. For the "Purchases" in particular, I think our SDKs could include a currency converter with data we update every few months. We're not promising exact numbers anyways, and currency conversion doesn't change too much, so an update every few months or so should be fine. I could even write a script to automate it. But please read the articles first and give me feedback what you think.

I don't want to commit to updating and maintaining these features for all SKDs right now, but we can talk about how to implement these kinds of features in a way that moves most of the work to the server so we don't duplicate it.

Thanks for your work, I'm gonna merge this now, since I already merged the other PR 😅

**Comment by Jeehut** [comment]
@winsmith Thank you for merging! 🎉 Sure, we can talk about the currency conversion.

But please note the original comment of this PR mentions that this should be merged together with https://github.com/TelemetryDeck/SwiftSDK/pull/154, which is currently still unmerged. The documentation pages https://telemetrydeck.com/docs/articles/preset-purchases/, and https://telemetrydeck.com/docs/articles/preset-errors/) now state that convenience APIs are available in the Swift SDK which are not.

We probably should merge https://github.com/TelemetryDeck/SwiftSDK/pull/154 and make a new release.

**Comment by winsmith** [comment]
I didn't see that one. You have the go :)

**Pull request merged**
